# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-04 21:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('gender', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='male', max_length=6)),
                ('danwei', models.CharField(max_length=20, verbose_name='\u5355\u4f4d\u540d\u79f0')),
                ('dishi', models.CharField(max_length=20, verbose_name='\u5355\u4f4d\u540d\u79f0')),
                ('address', models.CharField(default='', max_length=100, verbose_name='\u5355\u4f4d\u5730\u5740')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='\u624b\u673a\u53f7')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u4f1a\u8bae\u56de\u6267\u8868',
                'verbose_name_plural': '\u4f1a\u8bae\u56de\u6267\u8868',
            },
        ),
        migrations.AlterModelOptions(
            name='bdsuser',
            options={'verbose_name': '\u7528\u6237\u4fe1\u606f\u8868', 'verbose_name_plural': '\u7528\u6237\u4fe1\u606f\u8868'},
        ),
    ]
