# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-04 22:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0002_auto_20181004_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bdsuser',
            options={'verbose_name': '\u7528\u6237\u4fe1\u606f', 'verbose_name_plural': '\u7528\u6237\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': '\u4f1a\u8bae\u56de\u6267', 'verbose_name_plural': '\u4f1a\u8bae\u56de\u6267'},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='dishi',
            field=models.CharField(max_length=20, verbose_name='\u5730\u5e02'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
