# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-05 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0003_auto_20181004_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='\u90ae\u7bb1'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=20, verbose_name='\u53c2\u4f1a\u4eba\u5458'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u767b\u9646\u540d'),
        ),
    ]
