# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-06 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bds', '0004_auto_20181005_1851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BdsUser',
        ),
    ]
