# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-04 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181004_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
